### ISSUE TITLE
Example in documentation needs to have the comment removed on my system

### ISSUE THREAD

**Issue by ElleNajt** [AntonHakansson/org-nix-shell#6]
jThis package is awesome! I came across this bug in the example that's currently here: https://github.com/AntonHakansson/org-nix-shell/tree/main?tab=readme-ov-file#quickstart

```
#+name: nix-shell
#+begin_src nix
  { pkgs ? import <nixpkgs> {} }:
  pkgs.mkShell {
    buildInputs = [ pkgs.hello ];
  }
#+end_src

#+begin_src sh :nix-shell "nix-shell"  # load named nix-shell src block
  hello   # use 'hello' dependency
#+end_src
```

This does not work on my system since the comment "# load named nix-shell src block" seems to have been interpreted as part of the name :nix-shell is looking for. I get the error:

`‘"nix-shell" # comment’ src block not found in buffer`

Removing that comment from the sh block fixes the issue.

I also needed to add the :results verbatim header to my sh block to get cowsay to display correctly. (:results output as in the c and python example works also. ) Might be useful to include that in the example also.

**Comment by AntonHakansson** [comment]
> This package is awesome!

Thank you! And your suggestions are appreciated c:

> "nix-shell" # comment’ src block not found in buffer

Yes, this seems to be a bug in `org-nix-shell` when parsing header arguments. For now, I will remove the comment entirely and make it clearer that we're using a named `nix-shell` by context instead.

Something like:

```org
#+name: my-shell
#+begin_src nix
  { pkgs ? import <nixpkgs> {} }:
  pkgs.mkShell {
    buildInputs = [ pkgs.hello ];
  }
#+end_src

#+begin_src sh :nix-shell "my-shell"
  hello   # use 'hello' from 'my-shell'
#+end_src
```

> I also needed to add the :results verbatim header to my sh block to get `cowsay` to display correctly.

`cowsay`? Did you mean `hello`? Or are you referring to the example in the picture? The picture is just to showcase why this package is useful and shouldn't be interpreted as documentation. If you meant the `hello` package, it's because I didn't want to make things more complicated than absolutely necessary. Users can be expected to know org-babel enough to resolve this on their own. I might reconsider in the future but I'm currently leaning towards keeping it simple.

**Comment by ElleNajt** [comment]
> cowsay? Did you mean hello? Or are you referring to the example in the picture? 

Yes, I meant the example in the picture. Your reasoning makes sense to me -- I'm relatively new to org-babel so needing that header argument wasn't obvious to me, but your example file demonstrates using :results output, so that covers that base. :)
